// Code generated by the multiversx-sc build system. DO NOT EDIT.

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    trail_control
    (
        init => init
        markCheckpoint => mark_checkpoint
        getCheckpointsFor => get_checkpoints_for
        getAllWallets => get_all_wallets
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
